var cardList = {
  'ac': {value: 1,
        face: 1,
        suit: 'club' },
  'ah': {value: 1,
        face: 1,
        suit: 'heart' },
  'as': {value: 1,
        face: 1,
        suit: 'spade' },
  'ad': {value: 1,
        face: 1,
        suit: 'dimond' },
  '2c': {value: 2,
        face: 2,
        suit: 'club' },
  '2h': {value: 2,
        face: 2,
        suit: 'heart' },
  '2s': {value: 2,
        face: 2,
        suit: 'spade' },
  '2d': {value: 2,
        face: 2,
        suit: 'dimond' },
  '3c': {value: 3,
        face: 3,
        suit: 'club' },
  '3h': {value: 3,
        face: 3,
        suit: 'heart' },
  '3s': {value: 3,
        face: 3,
        suit: 'spade' },
  '3d': {value: 3,
        face: 3,
        suit: 'dimond' },
  '4c': {value: 4,
        face: 4,
        suit: 'club' },
  '4h': {value: 4,
        face: 4,
        suit: 'heart' },
  '4s': {value: 4,
        face: 4,
        suit: 'spade' },
  '4d': {value: 4,
        face: 4,
        suit: 'dimond' },
  '5c': {value: 5,
        face: 5,
        suit: 'club' },
  '5h': {value: 5,
        face: 5,
        suit: 'heart' },
  '5s': {value: 5,
        face: 5,
        suit: 'spade' },
  '5d': {value: 5,
        face: 5,
        suit: 'dimond' },
  '6c': {value: 6,
        face: 6,
        suit: 'club' },
  '6h': {value: 6,
        face: 6,
        suit: 'heart' },
  '6s': {value: 6,
        face: 6,
        suit: 'spade' },
  '6d': {value: 6,
        face: 6,
        suit: 'dimond' },
  '7c': {value: 7,
        face: 7,
        suit: 'club' },
  '7h': {value: 7,
        face: 7,
        suit: 'heart' },
  '7s': {value: 7,
        face: 7,
        suit: 'spade' },
  '7d': {value: 7,
        face: 7,
        suit: 'dimond' },
  '8c': {value: 8,
        face: 8,
        suit: 'club' },
  '8h': {value: 8,
        face: 8,
        suit: 'heart' },
  '8s': {value: 8,
        face: 8,
        suit: 'spade' },
  '8d': {value: 8,
        face: 8,
        suit: 'dimond' },
  '9c': {value: 9,
        face: 9,
        suit: 'club' },
  '9h': {value: 9,
        face: 9,
        suit: 'heart' },
  '9s': {value: 9,
        face: 9,
        suit: 'spade' },
  '9d': {value: 9,
        face: 9,
        suit: 'dimond' },
  '10c': {value: 10,
        face: 10,
        suit: 'club' },
  '10h': {value: 10,
        face: 10,
        suit: 'heart' },
  '10s': {value: 10,
        face: 10,
        suit: 'spade' },
  '10d': {value: 10,
        face: 10,
        suit: 'dimond' },
  'jc': {value: 10,
        face: 11,
        suit: 'club' },
  'jh': {value: 10,
        face: 11,
        suit: 'heart' },
  'js': {value: 10,
        face: 11,
        suit: 'spade' },
  'jd': {value: 10,
        face: 11,
        suit: 'dimond' },
  'qc': {value: 10,
        face: 12,
        suit: 'club' },
  'qh': {value: 10,
        face: 12,
        suit: 'heart' },
  'qs': {value: 10,
        face: 12,
        suit: 'spade' },
  'qd': {value: 10,
        face: 12,
        suit: 'dimond' },
  'kc': {value: 10,
        face: 13,
        suit: 'club' },
  'kh': {value: 10,
        face: 13,
        suit: 'heart' },
  'ks': {value: 10,
        face: 13,
        suit: 'spade' },
  'kd': {value: 10,
        face: 13,
        suit: 'dimond' },
}

module.exports = cardList